Repository digilandbali/digilandbali-web, pull requests merged in 2022-06, with the labels that each got.

#5 CI: added GitHub workflows
  .github/pull_request_template.md
  .github/workflows/mlc_config.json
  .github/workflows/tester.yml
Labels: ci

#9 Enabled SSG on next.js
  jsconfig.json
  pages/index.js
  pages/minting/[id].js
  pages/minting/index.js
  pages/projects/[id].js
  pages/projects/lima-beach/AboutLimaBeachSection.js
  pages/projects/lima-beach/BluePrintSection.js
  pages/projects/lima-beach/HomeSection.js
  pages/projects/lima-beach/LuxuryPropertySection.js
  pages/projects/lima-beach/MintSection.js
  pages/projects/lima-beach/MintingStageSection.js
  pages/projects/lima-beach/NFTFragmentSection.js
  pages/projects/lima-beach/PermissiveDocSection.js
  pages/projects/lima-beach/RoadmapSection.js
  pages/projects/lima-beach/SmartSysSection.js
  pages/projects/lima-beach/TokenDistSection.js
  pages/projects/lima-beach/UtilityNFTSection.js
  pages/projects/lima-beach/index.js
  src/components/ContentComponent.js
  src/components/ImageCarousel.js
  src/components/SectionBreak.js
Labels: enhancement, ci

#14 fix: replace nextjs image optimization
  pages/homepage/aboutSection.js
  pages/homepage/homeSection.js
  pages/homepage/sponsorSection.js
  pages/index.js
  src/components/NavbarComponent.js
Labels: enhancement

#15 ci: added firebase hosting
  .firebaserc
  .github/workflows/analyzer.yml
  .github/workflows/deployer.yml
  .github/workflows/mlc_config.json
  .github/workflows/tester.yml
  .gitignore
  README.md
  firebase.json
  package.json
Labels: ci
