Repository digilandbali/digilandbali-web, pull requests merged in 2022-08, with the labels that each got.

#54 Implemented feedbacks on UX when minting NFT
  src/components/ContentComponent.js
  src/helpers/metamask-interact.js
  src/hooks/use-mint.hooks.js
Labels: enhancement

#56 Added authentication when connecting wallet
  next.config.js
  package.json
  pages/api/hello.js
  src/components/ContentComponent.tsx
  src/components/Layout.js
  src/components/NavbarComponent.js
  src/helpers/error.ts
  src/helpers/metamask-interact.js
  src/hooks/use-auth.hooks.ts
  src/hooks/use-form.hooks.ts
  src/hooks/use-mint.hooks.js
  src/lib/api/auth.ts
  src/lib/api/index.ts
  src/lib/api/referral.ts
  src/store/index.ts
  yarn.lock
Labels: enhancement

#57 feat: stored minted NFT data on DB
  .env-template
  next.config.js
  src/components/ContentComponent.tsx
  src/hooks/use-mint.hooks.js
  src/lib/api/referral.ts
Labels: enhancement

#58 refactor: changed env var names
  .env-template
  next.config.js
  src/helpers/connectors.ts
  src/helpers/metamask-interact.js
  src/hooks/use-mint.hooks.js
Labels: enhancement

#59 ci: added new env
  .github/workflows/deployer.yml
  .github/workflows/publisher.yml
Labels: ci

#65 Added User Dashboard page
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/dashboard/index.tsx
  pages/index.js
  public/Unlockables/apart1.svg
  public/Unlockables/apart2.svg
  public/Unlockables/apart3.svg
  src/components/Meta.tsx
  src/components/NFTCard.module.css
  src/components/NFTCard.tsx
  src/components/PermissiveDocument.tsx
  src/components/UnlockableContent.tsx
  styles/globals.css
  tsconfig.json
  types/iron-session/index.d.ts
  yarn.lock
Labels: enhancement

#70 Fixed undefined data for users without nft
  src/components/UnlockableContent.tsx
Labels: bug, enhancement

#71 Fixed minor bugs and fetching owned NFT image
  .env-template
  next.config.js
  package.json
  pages/minting/[id].tsx
  src/components/ContentComponent.tsx
  src/components/NFTCard.module.css
  src/components/NFTCard.tsx
  src/components/UnlockableContent.tsx
  src/helpers/metamask-interact.js
  src/hooks/use-mint.hooks.js
  src/lib/api/auth.ts
  styles/globals.css
Labels: enhancement

#75 Handled UI based on feedbacks
  pages/_app.tsx
  pages/projects/lima-beach/MintingStageSection.js
  src/components/ConnectButton.tsx
  src/components/NavbarComponent.js
  src/components/PermissiveDocument.tsx
  src/components/UserMenuButton.tsx
  styles/globals.css
Labels: enhancement
